### PR TITLE
clean

### PR DESCRIPTION
**Pull request by Landon345**

### CODE REVIEW

**Comment by Landon345** [comment]
I'm going to add a create-react-app project after this.

**Comment by AseckOben** [comment]
Wow bro you did everything already 😥 I will need a little work through
bro. I really wish to master this.

**Comment by AseckOben** [comment]
It's okay , I just got my worries solved from the creat react app
documentation. I got a clue now.

**Comment by Landon345** [comment]
Glad to hear it!

**Comment by AseckOben** [comment]
Yeah I got much to learn from you bro.

**Pull request merged**
