### PR TITLE
added index.html and index.js files for react setup

### PR DESCRIPTION
**Pull request by Landon345**
This is the first pull request hopefully of many to come.

I was able to do this by doing: `git checkout -b feature` in the terminal.

This created a new branch called feature that I made changes to. Next I did: `git add .` to add all changes

Then: `git commit -m "added index.html and index.js files for react setup"`

Lastly I pushed it up to github by doing: `git push --set-upstream main feature`

Then it my changes showed up on github as a new branch that I can use to make a pull request and merge into the first branch.

### CODE REVIEW

**Comment by AseckOben** [comment]
nice so far bro.

**Comment by AseckOben** [comment]
What
 is our next step ?

**Comment by Landon345** [comment]
We can get all of the data we need from newsapi.org.

**Comment by AseckOben** [comment]
Okay, I should create a react app making use of it?

**Comment by AseckOben** [comment]
Bro hope you doing great today..  , like I said this my first official
project , to say I don't know how and where to use the newsapi.org

**Comment by Landon345** [comment]
Yup. That's the plan

**Comment by AseckOben** [comment]
Have you seen the app.js file I added on #feature for you to check it out ,

**Comment by Landon345** [comment]
Yeah, I just saw it. I think maybe we should use a full scale
create-react-app application instead of just using the cdns. This project
is big enough for us to do it this way. Here is what I am thinking: this
link will show you how to use create-react-app
https://reactjs.org/docs/create-a-new-react-app.html#create-react-app

**Comment by AseckOben** [comment]
Seen it, please lead bro, pls what am I to do now.

**Pull request merged**
